modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/UnlikePaladin/paladins-furniture/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "pfm"
version = "${version}"
displayName = "Paladin's Furniture"
authors = "UnlikePaladin"
description = '''
A Brand-New Furniture mod for Modern Minecraft where things are functional!
'''
itemIcon = "pfm:oak_chair"
logoFile = "icon.png"
credits = "Translators: lzyzl6, MIHONO, WrenXing, j-tap"
displayURL="https://github.com/UnlikePaladin/paladins-furniture/wiki"

[[dependencies.pfm]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pfm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[modproperties.pfm]
catalogueBackground="pfm_background.png"
catalogueImageIcon=""